services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - data:/data/db

  auth:
    build:
      context: ./backend/auth-api
      target: production
    ports:
      - '5000:5000'
    volumes:
      - ./backend/auth-api:/app:ro
    env_file:
     - ./backend/.env.local
     - ./backend/.env
    depends_on:
      - mongodb

  books:
    build:
      context: ./backend/books-api
      target: production
    ports:
      - '5001:5001'
    volumes:
      - ./backend/books-api:/app:ro
      - uploads:/app/uploads
    env_file:
     - ./backend/.env.local
     - ./backend/books-api/.env
    depends_on:
      - auth

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:5173'
    volumes:
      - ./frontend:/app/:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - books
      - auth

volumes:
  data:
  uploads: